### ISSUE TITLE
Using the test(CTE) enviroment

### ISSUE THREAD

**Issue by DavidVTurley** [vleeuwenmenno/OpenProvider.NET#2]
Hey nice work on the api!

I am trying to make a little app that uses it, but I have been having trouble getting the test environment(CTE) to work. I keep getting my authorization rejected. It works fine when I am on the live server though.

Did you run into the same issue by any chance, and if you did, did you find a solution to it??

Thanks!

**Comment by vleeuwenmenno** [comment]
Can you show an example of what you are trying to do?
I have yet to continue on this project of mine later I will add some samples but you should be able to prepare your env as follows:
```csharp
OP o = new OP();
bool authResult = o.Authenticate(lAPI.options.openProvider.user, lAPI.options.openProvider.pass);
if (!authResult)
{
    Console.WriteLine("Error authenticating for OpenProvider!");
    Environment.Exit(-100);
}
```

**Comment by vleeuwenmenno** [comment]
Have you managed to get your code working? I'll be closing this issue, you are free to reopen it if you need any assistance.
